baseURL = "https://henryhe.me/"
languageCode = "en-us"
title = "Field Notes"
theme = "hugo-theme-stack"
enableEmoji = true
copyright = "Henry He"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[taxonomies]
tag = "tags"
series = "series"
category = "categories"

[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
    [menu.main.params]
        icon = "home"

[outputs]
    home = ["HTML", "RSS"]

[services]
    [services.disqus]
        shortname = "spaceblog-1"