baseURL = "https://henryhe.me/"
languageCode = "en-us"
title = "s p a c e"
theme = "hugo-vitae"
paginate = 5

copyright = "🌊 Henry He 2021"

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
enableEmoji = true

googleAnalytics = "UA-127793104-1"
disqusShortname = "spaceblog-1"

[markup.goldmark.renderer]
	unsafe = true

[taxonomies]
	tag = "tags"
	series = "series"

[params]
	subtitle = "a blog"
	author = "Henry He"
	github = "https://github.com/henryhe1"
	twitter = "@henryhe_"
	sitename = "s p a c e"

	# Optional 80x80 avatar image.
	avatar = "/img/henry.png"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]

	customCSS = "css/custom.css"  # Custom CSS applied to default styles.

# Nav.
[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "all posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "about"
url = "/about"
weight = 3

[[menu.main]]
name = "tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "series"
url = "/series"
weight = 5

[[menu.main]]
name = "music"
url = "/music"
weight = 6

[[menu.main]]
name = "peds-vitals"
url = "/pedsvitals"
weight = 7

[[params.social]]
name = "Twitter"
icon = "fab fa-twitter"
url = "https://twitter.com/henryhe_"

[[params.social]]
name = "IG"
icon = "fab fa-instagram"
url = "https://instagram.com/henryhe_"

[[params.social]]
name = "Spotify"
icon = "fab fa-spotify"
url = "https://open.spotify.com/artist/3CB8L5exWFpxIpacfVsE0l?si=bjZnucKMSmWGkirDaI5ulQ"

[[params.social]]
name = "SoundCloud"
icon = "fab fa-soundcloud"
url = "https://soundcloud.com/staraniz"

[[params.social]]
name = "Medium"
icon = "fab fa-medium"
url = "https://medium.com/@henryhe_"

[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/henryhe1"



# [[params.social]]
# name = "Main Website"
# icon = "fas fa-home"
# url = "https://henryhe.me"




